language: python
python:
  - "2.7"
env:
  matrix:
  - CONDOR_SERIES=8.8  # stable
  - CONDOR_SERIES=8.7  # development
install:
  - pip install pyopenssl htcondor~=$CONDOR_SERIES
  - make install_python
  - cp condor/condor_meter{,.py}  # for importing condor_meter
script:
  - test/run_unit_tests.sh

